[pytest]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true

# 1. Настройка базового запуска (командная строка по умолчанию)
# -v: подробный вывод, -s: выводить print() в консоль, --alluredir: путь для отчетов Allure
addopts = -v -s --alluredir=output/allure-results --tb=short

# 2. Определение корневых папок для поиска тестов (ускоряет сборку проекта)
testpaths = tests src/tests

# 3. Шаблоны для поиска файлов, классов и тестовых методов
python_files = test_*.py *_test.py
python_classes = Test* *Tests
python_functions = test_*

# 4. Настройка логирования в консоли в реальном времени
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

# 5. Регистрация тегов (маркеров)
markers =
    smoke: Быстрые критические тесты (Smoke testing)
    regression: Полные регрессионные тесты (Regression testing)
    api: Тесты для проверки API (интеграционные / компонентные)
    ui: Тесты для проверки пользовательского интерфейса (Web UI)
    e2e: Сквозные тесты (End-to-End)
    db: Тесты, проверяющие напрямую базу данных
    positive: Позитивные сценарии
    negative: Негативные сценарии
